---
name: Draft Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draft-release:
    name: Draft Release
    uses: raven-actions/.workflows/.github/workflows/release-draft.yml@main
