---
name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - converted_to_draft
      - ready_for_review
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: raven-actions/.workflows/.github/workflows/__lint.yml@main
    secrets: inherit
