---
name: Linter

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - converted_to_draft
      - ready_for_review
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main

jobs:
  linter:
    name: Linter
    uses: raven-actions/.workflows/.github/workflows/__linter.yml@main
    secrets: inherit
