---
name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  lint:
    name: Lint
    uses: raven-actions/.workflows/.github/workflows/__lint.yml@main
    secrets: inherit
