---
name: Stale

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:
  
jobs:
  stale:
    name: Stale
    uses: raven-actions/.workflows/.github/workflows/__stale.yml@main
    secrets: inherit
